---
# D3js Test playbook
- hosts: staging_d3js_test
  roles:
    - common
    - nginx
    - python
    - nodejs
    - nginx-passenger
    - application
  remote_user: ubuntu
  become: yes
  gather_facts: false
  pre_tasks:
    - raw: apt-get install python-minimal aptitude -y
    # action: setup will gather facts after python2 has been installed
    - action: setup